### ISSUE TITLE
Generic components

### ISSUE THREAD

**Issue by elertan** [Mcat12/shaku#2] opened 2020-05-29 19:03 UTC
I'm trying to use generics on the components I want to have injectable by shaku.

e.g.
```rs
pub trait RegisterService: shaku::Interface {}

#[derive(shaku::Component)]
#[shaku(interface = RegisterService)]
pub struct RegisterServiceImpl<E>
where
    E: Executor<Database = Postgres> + RefExecutor<'static, Database = Postgres>,
{
    executor: E,
}

impl<E> RegisterService for RegisterServiceImpl<E> where
    E: Executor<Database = Postgres> + RefExecutor<'static, Database = Postgres>
{
}
```

`E` is a database executor provided by sqlx, which makes it possible for the executor to be either a sql connection, a pool or a transaction.
This functionality is necessary in order to use these components in all different scenarios, e.g. where a transaction is required over a range over different component method calls.

That said this would also require the container creation to be relatively cheap (as a functional requirement), as the executor needs to be changed from the connection pool to a transaction at some point.

Any idea how to go about this, or if this is even possible with the current state of shaku?
I've been thinking of using dynamic dispatch instead of generics, but I'd like to not have that runtime overhead if possible.

**Comment by Mcat12** [comment] 2020-05-29 19:37
So, this is possible and can be done with recent versions of shaku. There is no change in performance, and you can easily swap out different generic implementations at startup using [`with_component_override`] like usual. However, the derive macros and `module` macro don't support generics on the implementation side yet (only in the interface type) so you need to write all of that code manually until support is added.

Also a note, you're already using dynamic dispatch by using the `RegisterService` interface instead of `RegisterServiceImpl` directly, but I do agree that we should try to avoid more dynamic dispatch.

I wrote a PoC test which may help you:
https://github.com/Mcat12/shaku/commit/2e6844f7dea28849b84a236cc86958c0e4f5b6bf
Note that it's based on v0.4.0 (recently released), but should work just fine on v0.3.x.

[`with_component_override`]: https://docs.rs/shaku/0.4.0/shaku/struct.ModuleBuilder.html#method.with_component_override

**Comment by Mcat12** [comment] 2020-05-29 20:14
Ok, so here's an easy way to still use the `module` macro:
```rust
type RegisterServiceImplType = RegisterServiceImpl<()>;

module! {
    MyModule {
        components = [RegisterServiceImplType],
        providers = []
    }
}
```

The `module` macro re-uses the component/provider names as identifiers in a few places, so since `RegisterServiceImpl<()>` is not a valid identifier the macro would fail. Hiding it behind a type alias works though!

**Comment by elertan** [comment] 2020-05-29 20:34
Thanks for the POC.
Definitely seems like a shot in the right direction!

However I can't type alias with `()` as it requires the generic to impl `Executor` in my case. I can't give a concrete type when using the module macro, it has to be during the building of the container, otherwise I wouldn't be able to swap out the executor.

**Comment by elertan** [comment] 2020-05-29 20:42
To give a better example,  I would need:
```rs
type RegisterServiceImplType = RegisterServiceImpl<sqlx::Pool<sqlx::PgConnection>>;
type RegisterServiceImplType = RegisterServiceImpl<&sqlx::PgConnection>;
type RegisterServiceImplType = RegisterServiceImpl<&sqlx::Transaction>;
// I might be off with the actual types

module! {
    MyModule {
        components = [RegisterServiceImplType],
        providers = []
    }
}
```

**Comment by elertan** [comment] 2020-05-29 21:06
This is more so related to sqlx, but I just figured out having just a Executor would not be enough for what I'm trying to achieve, as I need to be able to create a/re-use an existing transaction, and executor does not support that. But still would love to know how to make this work either way.

**Comment by Mcat12** [comment] 2020-05-29 21:18
Perhaps you could make a new public repository with a minimal reproduction so I could try my hand at the problem directly?

I have found a way to modify the `module` macro to support generic types, so the hard part is almost done on that front.

From your `type RegisterServiceImplType = ... type RegisterServiceImplType = ... type RegisterServiceImplType = ...` example it looks like you're trying to put multiple `RegisterService` implementations into the same module? You can only have one implementation per interface type, but you could make the interface generic (`RegisterService<E>`). Also, instead of using references (`&`), which imply lifetimes, you would need to use something like `Arc` which has a `'static` lifetime. The framework can't handle non-`'static` lifetimes in services currently.

**Comment by elertan** [comment] 2020-05-30 01:15
I will make an attempt on creating a sample project tomorrow if I have the time to do so. I'll link it here once it's ready!

**Comment by elertan** [comment] 2020-05-30 09:46
This should show what I'm trying to achieve.
https://github.com/elertan/shaku-generic-components

This is more related to another library I want to consume, but I figured I'd link it here as well in case it helps getting my point across even better.
https://github.com/launchbadge/sqlx/issues/351

**Comment by Mcat12** [comment] 2020-05-30 15:18
I forked it and made two PRs to show two different ways to solve this problem (though one strategy is more powerful):
- https://github.com/elertan/shaku-generic-components/pull/1
- https://github.com/elertan/shaku-generic-components/pull/2

We can discuss the specifics of each strategy in the respective PRs and use this issue when talking generally.

**Comment by Mcat12** [comment] 2020-06-01 22:04
v0.4.1 has been released with support for generics in modules and components/providers when using macros. @elertan is there anything else before we close this issue?

**Comment by elertan** [comment] 2020-06-01 22:09
Maybe we could provide an example binary with generics as well in the repo, so others will have an easier time implementing it themselves.
But besides that, looks good to me. 👍

**Comment by Mcat12** [comment] 2020-06-01 22:14
I do have some tests, does that work?
- [`generic_modules.rs`]
- [`generic_submodules.rs`]

[`generic_modules.rs`]: https://github.com/Mcat12/shaku/blob/master/shaku/tests/generic_modules.rs
[`generic_submodules`]: https://github.com/Mcat12/shaku/blob/master/shaku/tests/generic_submodules.rs

**Comment by elertan** [comment] 2020-06-01 23:17
I've added another test as a PR, which focuses on simplicity, see https://github.com/Mcat12/shaku/pull/3 . Feel free to include/modify that one as well.

**Comment by elertan** [comment] 2020-06-02 19:00
I was workering on the example for the use of sqlx, but I'm still facing some issues with the `Default` requirement and the fact that the macro still doesn't fully support the entire generic type (associated types).

Feel free to take a look at this to get a rough idea of what I'm doing: https://github.com/elertan/shaku/blob/sqlx_example/examples/sqlx_generic_connection/src/main.rs

**Comment by Mcat12** [comment] 2020-06-02 22:25
For `Default`, you could do the trick where you use `#[shaku(default = unreachable!())]`.

Generic associated types may be doable, and I'll try to add them, but it would be easier/more accurate if the `module` macro was a procedural macro instead of macro_rules. What do think of this change? I have mostly avoided it because macro_rules lets it be more declarative, doesn't require `syn`, `quote`, and friends, and should technically be able to do the task (even though it might get a pretty complex).

**Comment by Mcat12** [comment] 2020-06-06 16:24
Update on making `module` support associated types, I don't think it's possible with macro_rules. The macro_rules parser has certain "follow-set ambiguity restrictions" which restrict what separators you can use for certain items, like `ty`:
> `path` and `ty` may only be followed by one of: `=>`, `,`, `=`, `|`, `;`, `:`, `>`, `>>`, `[`, `{`, `as`, `where`, or a macro variable of `block` fragment specifier.

https://doc.rust-lang.org/reference/macros-by-example.html#follow-set-ambiguity-restrictions

Generic bounds are separated by `+`, which is not a valid separator. To overcome this, I was manually matching against the bound with `$m_bound:ident $(< $($m_bound_inner:ty),* >)?`. This only supports types without associated types, because `ty` doesn't match an associated type bound like `Database = MyDatabase`.

I tried adding support, which made it a considerably uglier:
```
$m_bound:ident $(< $($($m_bound_inner:ty),* ,)? $($m_bound_aty_ident:ident = $m_bound_aty_ty:ty),* >)?
```

Unfortunately, the macro_rules parser runs into ambiguity when it tries to decide if the item is an associated type identifier (`ident`) or a regular type (`ty`):
```
error: local ambiguity: multiple parsing options: built-in NTs ty ('m_bound_inner') or ident ('m_bound_aty_ident').
  --> shaku/tests/associated_types_in_generic_bounds.rs:37:28
   |
37 |     MyModule<C: Connection<Database = MyDatabase> + Default> {
   |                            ^^^^^^^^
```

I think it's time to move the `module` macro to a procedural macro, which would solve this issue.

**Comment by Mcat12** [comment] 2020-06-07 02:58
`master` now uses a proc-macro for `module`, and I've added a test for associated types in generic bounds:
https://github.com/Mcat12/shaku/blob/09bef509122a48b1ed8e082e9131e7535fe227ad/shaku/tests/associated_types_in_generic_bounds.rs

I'll release this as 0.5.0 at some point, perhaps pending your feedback @elertan?

**Comment by Mcat12** [comment] 2020-06-19 22:34
[Shaku v0.5.0](https://github.com/Mcat12/shaku/blob/v0.5.0/CHANGELOG.md#050---2020-06-19) has been released.

**Closed by Mcat12** 2020-06-19 22:34 UTC
